---
title: "Bitcoin OTC Personalized Trading Partner Recos"
author: "Michelle Skaf"
date: "8/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/MSBA2022/DataMining")
```

```{r include=FALSE }
library(recosystem)
```


#2 load data
```{r  }
otc=read.csv("bitcoin_otc.csv",sep=',',header=F)
colnames(otc)=c("sender","receiver","rating","time")
dim(otc) #35592 ratings
n=35592
max(otc[,1]) #6000 senders
max(otc[,2]) #6005 receivers
```


# 3. Split the data for training and testing
```{r  include=FALSE}
set.seed(666)
n_train=floor(n*0.8)
trainID=sample(1:n,n_train)
testID=setdiff(1:n,trainID)
train_set=otc[trainID,]
test_set=otc[testID,]
```


#4. Running matrix factorization
```{r  }
r = Reco()
#Tuning
opts = r$tune(data_memory(train_set[,1],train_set[,2],train_set[,3],index1=TRUE), 
              opts = list(loss="l2",dim = c(1, 2, 3), lrate = 0.1,nthread = 1, niter = 10))
opts
#Training: using the tuned parameters
set.seed(123)
RS3=r$train(data_memory(train_set[,1],train_set[,2],train_set[,3],index1=TRUE), opts = c(loss="l2",opts$min, nthread = 1, niter = 20))
#Predicting
pred_rvec = r$predict(data_memory(test_set[,1],test_set[,2],test_set[,3],index1=TRUE), out_memory())
#Evaluating the performance of the prediction with RMSE
sqrt(mean((test_set[,3]-pred_rvec)^2)) #2.84; a very small RMSE, given the rating range is -10 to 10

```


#5. Manually check a few predictions
```{r  }
#Calculate P and Q (latent-factor matrices)
P_file = out_file(tempfile())
Q_file = out_file(tempfile())
r$output(P_file, Q_file)
P0=read.table(P_file@dest, header = FALSE, sep = " ")
Q0=read.table(Q_file@dest, header = FALSE, sep = " ")
P=matrix(as.numeric(unlist(P0)),dim(P0))
Q=matrix(as.numeric(unlist(Q0)),dim(Q0))
#Manually check predictions with P and Q
test_set[1:11,]

#what are sender 1's weights of the 3 latent factors?
P[1,]

#what are receiver 15's weights of the 3 latent factors?
Q[15,]

# we can multiply and sum these to get the predicted rating of 1 to 15
sum(P[1,]*Q[15,])

#what are sender 1's weights of the 3 latent factors?
P[2,]

#what are receiver 15's weights of the 3 latent factors?
Q[20,]

#lets try 2 to 20
sum(P[2,]*Q[20,]) #Compare this value with the actual rating: 5
```


